query getChatList(
  $companyId: String!
  $pagination: CursorPagination
  $status: ChatStatusType!
) {
  chats(companyId: $companyId, pagination: $pagination, status: $status) {
    items {
      id
      lastMessage {
        id
        author {
          id
          firstname
        }
        date
        isComment
        sticker {
          url
        }
        text
      }
      subscriber {
        id
        source {
          firstname
          lastname
          photo
          type
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}
