###############
## MUTATIONS ##
###############
mutation ADD_BLOCK($block: CreateBlockInput!, $flowId: String!) {
  addBlock(block: $block, flowId: $flowId) {
    id
    blocks {
      id
      position {
        x
        y
      }
      title
      type
    }
  }
}

mutation ADD_EDGE(
  $sourceId: String!
  $sourceElementId: String
  $sourceHandleId: String
  $targetId: String!
) {
  addEdge(
    edge: {
      sourceId: $sourceId
      sourceElementId: $sourceElementId
      sourceHandleId: $sourceHandleId
      targetId: $targetId
    }
  ) {
    id
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
  }
}

mutation ADD_ELEMENT($blockId: String!, $element: ElementInput!) {
  addElement(blockId: $blockId, element: $element) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
      position {
        x
        y
      }
      title
      type
    }
  }
}

mutation CREATE_FLOW($companyId: String!, $flow: FlowInput!) {
  createFlow(companyId: $companyId, flow: $flow) {
    id
    status
    title
  }
}

mutation DELETE_FLOW($flowId: String!) {
  deleteFlow(flowId: $flowId)
}

mutation PUBLISH_FLOW($flowId: String!) {
  publishFlow(flowId: $flowId)
}

mutation REMOVE_BLOCK($blockId: String!) {
  removeBlock(blockId: $blockId) {
    id
    blocks {
      id
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
  }
}

mutation REMOVE_EDGE($edgeId: String!) {
  removeEdge(edgeId: $edgeId) {
    id
    edges {
      id
    }
  }
}

mutation REMOVE_ELEMENT($elementId: String!) {
  removeElement(elementId: $elementId) {
    id
    blocks {
      id
      elements {
        id
      }
    }

    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
  }
}

mutation UPDATE_BLOCK($blockId: String!, $block: UpdateBlockInput!) {
  updateBlock(blockId: $blockId, block: $block) {
    id
    blocks {
      id
      position {
        x
        y
      }
      title
    }
  }
}

mutation UPDATE_ELEMENT($elementId: String!, $payload: JSON!) {
  updateElement(elementId: $elementId, payload: $payload) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
    }
  }
}

mutation UPDATE_FLOW($flowId: String!, $flow: FlowInput!) {
  updateFlow(flowId: $flowId, flow: $flow) {
    id
    status
    title
  }
}

#############
## QUERIES ##
#############
query GET_FLOW($flowId: String!, $flowMode: FlowMode!) {
  flow(flowId: $flowId, flowMode: $flowMode) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
      position {
        x
        y
      }
      title
      type
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
    status
    title
  }
}

query GET_FLOWS($companyId: String!) {
  flows(companyId: $companyId) {
    id
    status
    title
  }
}
