mutation ADD_COLLABORATOR($companyId: String!, $userId: String!) {
  addCollaborator(userId: $userId, companyId: $companyId) {
    id
    role
    user {
      id
      email
      firstname
      lastname
      username
    }
  }
}
