subscription SUB_CHAT_UPDATED($companyId: String!, $status: ChatStatusType!) {
  chatUpdated(companyId: $companyId, status: $status) {
    id
    lastMessage {
      id
      author {
        id
        firstname
      }
      date
      isComment
      sticker {
        url
      }
      text
    }
    status
    subscriber {
      id
      source {
        firstname
        lastname
        photo
        type
      }
    }
  }
}
