query getSubscriberList($companyId: String!) {
  subscribers(companyId: $companyId) {
    id
    createdAt
    messagePolicy
    source {
      id
      firstname
      lastname
      photo
      type
      username
    }
  }
}
