query getMessageList($chatId: String!, $pagination: CursorPagination) {
  messages(chatId: $chatId, pagination: $pagination) {
    items {
      id
      author {
        id
        firstname
        lastname
        photo
        username
      }
      date
      isComment
      isOutcoming
      status
      sticker {
        url
      }
      text
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}
