query getMessageList($chatId: String!, $pagination: PaginationInput!) {
  messages(chatId: $chatId, pagination: $pagination) {
    id
    author {
      id
      firstname
      lastname
      photo
      username
    }
    date
    isComment
    isOutcoming
    status
    text
  }
}
