subscription subMessageNew($chatId: String!) {
  messageNew(chatId: $chatId) {
    id
    author {
      id
      firstname
      lastname
      photo
      username
    }
    date
    isComment
    isOutcoming
    status
    sticker {
      url
    }
    text
  }
}
