query GET_CURRENT_SUBSCRIPTION($companyId: String!) {
  currentSubscription(companyId: $companyId) {
    id
    cancelDate
    next {
      billDate
      price
    }
    payments {
      id
      amount
      checkoutId
      orderId
      receiptUrl
      status
      tax
      type
    }
    plan {
      id
      features
      price
      title
      type
    }
    status
    updateUrl
  }
}
