query getSubscriberById($companyId: String!, $subscriberId: String!) {
  fields(companyId: $companyId) {
    id
    title
    type
  }

  fieldTypes {
    color
    value
  }

  subscriber(subscriberId: $subscriberId) {
    id
    fields {
      fieldId
      value
    }
    messagePolicy
    source {
      id
      firstname
      lastname
      link
      photo
      type
      username
    }
    tags
  }

  tags(companyId: $companyId) {
    id
    color
    title
  }
}
