mutation setField($fieldId: String!, $subscriberId: String!, $value: String!) {
  setField(fieldId: $fieldId, subscriberId: $subscriberId, value: $value) {
    id
    fields {
      fieldId
      value
    }
  }
}
