query GET_MESSAGE_LIST(
  $chatId: String!
  $pagination: CursorPagination
  $search: String
) {
  messages(chatId: $chatId, pagination: $pagination, search: $search) {
    items {
      id
      author {
        id
        firstname
        lastname
        photo
        username
      }
      date
      isComment
      isOutcoming
      status
      sticker {
        url
      }
      text
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}
