subscription SUB_MESSAGE_UPDATED($chatId: String!) {
  messageUpdated(chatId: $chatId) {
    id
    author {
      id
      firstname
      isBot
      lastname
      photo
      username
    }
    date
    isComment
    isOutcoming
    status
    sticker {
      url
    }
    text
  }
}
