query getFlowById($flowId: String!) {
  flow(flowId: $flowId) {
    id
    blocks {
      id
      elements {
        id
        payload {
          ... on StartKeyword {
            operator
            value
          }
        }
        type
      }
      position {
        x
        y
      }
      title
      type
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
    title
  }
}
