mutation ADD_ELEMENT($blockId: String!, $element: ElementInput!) {
  addElement(blockId: $blockId, element: $element) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
      position {
        x
        y
      }
      title
      type
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
    title
  }
}
