mutation REMOVE_ELEMENT($elementId: String!) {
  removeElement(elementId: $elementId) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
      position {
        x
        y
      }
      title
      type
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
    title
  }
}
