mutation updateBlock($blockId: String!, $block: UpdateBlockInput!) {
  updateBlock(blockId: $blockId, block: $block) {
    id
    blocks {
      id
      position {
        x
        y
      }
      title
    }
  }
}
