mutation UPDATE_ELEMENT($elementId: String!, $payload: JSON!) {
  updateElement(elementId: $elementId, payload: $payload) {
    id
    blocks {
      id
      elements {
        id
        payload
        type
      }
      position {
        x
        y
      }
      title
      type
    }
    edges {
      id
      sourceId
      sourceElementId
      sourceHandleId
      targetId
    }
    title
  }
}
