mutation sendMessage($chatId: String!, $isComment: Boolean, $text: String!) {
  sendMessage(chatId: $chatId, isComment: $isComment, text: $text) {
    id
    author {
      id
      firstname
      lastname
      photo
      username
    }
    date
    isComment
    isOutcoming
    status
    text
  }
}
